---
- name: install software
  become: yes
  package:
    name:
      - alacritty
      - sxhkd
      - polybar
        # - TODO move away from manjaro
        # - dmenu
        # - bspwm
    state: present

- name: grab dotfiles
  git:
    repo: https://github.com/patwoodburn/dotfiles.git
    dest: "/home/{{ username }}/dotfiles"

- name: config alacritty
  file:
    src: "/home/{{ username }}/dotfiles/alacritty.yml"
    dest: "/home/{{ username }}/.config/alacritty/alacritty.yml"
    state: link

- name: config sxkbd
  file:
    src: "/home/{{ username }}/dotfiles/sxhkdrc"
    dest: "/home/{{ username }}/.config/sxhkd/sxkbdrc"
    state: link

- name: config bspwm
  file:
    src: "/home/{{ username }}/dotfiles/bspwmrc"
    dest: "/home/{{ username }}/.config/bspwm/bspwmrc"
    state: link
