---
- name: install software
  become: yes
  package:
    name:
      - vim
      - tmux
      - git
      - zsh
    state: present

- name: get zsh
  command: 'git clone-c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh'
  args:
    chdir: "/home/{{ username }}/"
    creates: "/home/{{ username }}/.oh-my-zsh"

- name: set permisions of oh-my-zsh
  file:
    path: "/home/{{ username }}/.oh-my-zsh"
    mode: 'go-w'
    recurse: yes
